config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  ALBUM_TYPES = ["Live", "Studio"]

  validates :name, :album_type, :band, presence: true
  validates :album_type, inclusion: {in: ALBUM_TYPES}

  belongs_to :band

  has_many :tracks,
    dependent: :destroy

  def self.album_types
    ALBUM_TYPES
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base

  validates :name, :album, presence: true

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token

  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true

  def self.generate_session_token
      SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.where(email: email).first

    return user if user && user.is_password?(password)

  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
    album = Album.new(album_params)

    if album.save
      redirect_to album_url(album)
    else
      redirect_to new_band_album_url
    end
  end

  def new
  end

  def show
    @album = Album.find_by(id: params[:id])
  end

  def edit
    @album = Album.find_by(id: params[:id])
  end

  def update
    album = Album.find_by(id: params[:id])

    if album.update(album_params)
      redirect_to album_url(album)
    else
      redirect_to edit_album_url
    end
  end

  def destroy
    band = Album.find_by(id: params[:id]).band
    
    if Album.find_by(id: params[:id]).destroy
      redirect_to band_url(band)
    else
      redirect_to band_url(band)
    end
  end

  private
  def album_params
    params.require(:albums).permit(:name, :band_id, :album_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def login_user!(user)
      user.reset_session_token!
      session[:session_token] = user.session_token
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def new
  end

  def create
    band = Band.new(band_params)

    if band.save
      redirect_to bands_url
    else
      redirect_to new_band_url
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
  end

  def edit
    @band = Band.find_by(id: params[:id])
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      redirect_to edit_band_url
    end
  end

  def destroy
    if Band.find_by(id: params[:id]).destroy
      redirect_to bands_url
    else
      redirect_to bands_url
    end
  end


  private
  def band_params
    params.require(:bands).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email],
                                    params[:user][:password])
    if user
      login_user!(user)
      redirect_to user_url
    else
      render :new
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user)
    else
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_login_or_register(new_user)
    if new_user
      html_string = "<form action='#{users_url}' method='post'>"
    else
      html_string = "<form action='#{session_url}' method='post'>"
    end

    html_string
  end

  def button_login_or_register(new_user)
    if new_user
      html_string = "<button type='submit'>Register User</button>"
    else
      html_string = "<button type='submit'>Login</button>"
    end

    html_string
  end

  def form_new_or_edit(new_band, band)
    if new_band
      html_string = "<form action='#{bands_url}' method='post'>"
    else
      html_string = "<form action='#{band_url(band)}' method='post'>"
    end

    html_string
  end

  def button_new_or_edit(new_band)
    if new_band
      html_string = "<button type='submit'>Add Band</button>"
    else
      html_string = "<button type='submit'>Edit Band</button>"
    end

    html_string
  end

  def album_form_new_or_edit(new_album, album)
    if new_album
      html_string = "<form action='#{albums_url}' method='post'>"
    else
      html_string = "<form action='#{album_url(album)}' method='post'>"
    end

    html_string
  end

  def album_button_new_or_edit(new_album)
    if new_album
      html_string = "<button type='submit'>Add Album</button>"
    else
      html_string = "<button type='submit'>Edit Album</button>"
    end

    html_string
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album_form.html.erb
<%= album_form_new_or_edit(new_album, album).html_safe %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
  <input type="hidden" name="albums[band_id]" value="<%= params[:band_id]  %>"/>
  <% unless new_album %>
    <input type="hidden" name="_method" value="patch"/>
  <% end %>

  <label for="albums[name]">Album Name:</label>
  <input type="text" name="albums[name]" value="<%= album.name %>"/>
  <br>
  <% Album.album_types.each do |album_type| %>
    <input type="radio" name="albums[album_type]" value="<%= album_type %>"<%= "checked='checked'" if album_type == album.album_type %>> <%= album_type %><br>
  <% end %>

  <%= album_button_new_or_edit(new_album).html_safe %>

app/views/albums/edit.html.erb
<%= render "album_form", new_album: false, album: @album%>

app/views/albums/new.html.erb
<%= render "album_form", new_album: true, album: Album.new %>

app/views/albums/show.html.erb
<h1><%= @album.name  %> by <%= @album.band.name %> </h1>
  <ul>
    <% @album.tracks.each do |track|%>
      <li> <a href="<%= track_url(track) %>"><%= track.name %></a>
    <% end %>
  <ul>

  <%= button_to "Add an track to this album", new_album_track_url(@album), method: :get %>
  <%= button_to "Back to #{@album.band.name}", band_url(@album.band), method: :get %>
  <%= button_to "Edit this album", edit_album_url, method: :get %>
  <%= button_to "Delete this album", album_url, method: :delete %>

app/views/bands/_band_form.html.erb
<%= form_new_or_edit(new_band, band).html_safe %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
  <% unless new_band  %>
    <input type="hidden" name="_method" value="patch"/>
  <% end %>
  <label for="bands[name]">Band Name:</label>
  <input type="text" name="bands[name]" value="<%= band.name %>"/>
  <br>

  <%= button_new_or_edit(new_band).html_safe %>

app/views/bands/edit.html.erb
<%= render "band_form", new_band: false, band: @band %>

app/views/bands/index.html.erb
<h1> Bands </h1>
  <ul>
    <% @bands.each do |band|%>
      <li> <a href="<%= band_url(band) %>"><%= band.name %></a>
    <% end %>
  <ul>

  <%= button_to "Add a Band", new_band_url, method: :get %>

app/views/bands/new.html.erb
<%= render "band_form", new_band: true, band: Band.new %>

app/views/bands/show.html.erb
<h1><%= @band.name  %></h1>

  <ul>
    <% @band.albums.each do |album|%>
      <li> <a href="<%= album_url(album) %>"><%= album.name %></a>
    <% end %>
  <ul>

  <%= button_to "Add an album to this band", new_band_album_url(@band), method: :get %>
  <%= button_to "Back to all bands", bands_url, method: :get %>
  <%= button_to "Edit this band", edit_band_url, method: :get %>
  <%= button_to "Delete this band", band_url, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_login.html.erb
<%= form_login_or_register(new_user).html_safe %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>

  <label for="user[email]">Email:</label>
  <input type="text" name="user[email]" />
  <br>

  <label for="user[password]">Password:</label>
  <input type="password" name="user[password]" />
  <br>

  <%= button_login_or_register(new_user).html_safe %>

app/views/users/new.html.erb
<%= render "partials/login", new_user: true %>

app/views/users/show.html.erb
<h1> <%= @user.email %> <h1>
<%= button_to "Logout", session_url, method: :delete %>